# Generated by Django 4.1 on 2022-11-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
