# Generated by Django 4.1 on 2022-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_owner_task_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('store', models.CharField(max_length=200)),
                ('buy_date', models.DateField()),
            ],
        ),
    ]
