# Generated by Django 4.1 on 2022-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_shopping_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
