# Generated by Django 4.1 on 2022-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'course_offerings',
            },
        ),
    ]
